use std::env;
use std::fs::{self, File};
use std::io::{self, BufWriter, Write};
use std::path::PathBuf;

fn main() -> io::Result<()> {
    println!("cargo::rerun-if-changed=WORD.LST");

    let source = fs::read_to_string("WORD.LST")?;
    let output = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo sets OUT_DIR"));
    let mut generated = BufWriter::new(File::create(output.join("words.rs"))?);
    writeln!(generated, "/// Five-letter ASCII words from WORD.LST, normalized at build time.")?;
    writeln!(generated, "pub static WORDS: &[Word] = &[")?;
    for word in source.lines() {
        if word.len() == 5 && word.bytes().all(|byte| byte.is_ascii_alphabetic()) {
            // Only ASCII letters reach the generated byte-string literal.
            writeln!(generated, "    Word(*b\"{}\"),", word.to_ascii_lowercase())?;
        }
    }
    writeln!(generated, "];")?;
    generated.flush()
}
